In [1]:
import numpy as np
import pandas as pd

In [2]:
dict1 = {
    "name":['maya', 'chaaya', 'savita', 'nirmala'],
    "marks":[34, 56, 87, 21],
    "city":['patna', 'jhansi', 'bhind', 'gwalior']
}

In [3]:
df = pd.DataFrame(dict1)

In [4]:
df

      name  marks     city
0     maya     34    patna
1   chaaya     56   jhansi
2   savita     87    bhind
3  nirmala     21  gwalior

In [5]:
df.to_csv('friends_no_index.csv',index=False)

In [6]:
df.head(2)

     name  marks    city
0    maya     34   patna
1  chaaya     56  jhansi

In [7]:
df.tail(3)

      name  marks     city
1   chaaya     56   jhansi
2   savita     87    bhind
3  nirmala     21  gwalior

In [8]:
df.describe()

           marks
count   4.000000
mean   49.500000
std    28.873286
min    21.000000
25%    30.750000
50%    45.000000
75%    63.750000
max    87.000000

In [9]:
trains = pd.read_csv('trains.csv')

In [10]:
trains

   train no.  speed  no. of stations     city
0      45125    125               15    patna
1      79882     87               28   jhansi
2      89645    364               12    bhind
3      54621     55                8  gwalior

In [11]:
trains['speed']

0    125
1     87
2    364
3     55
Name: speed, dtype: int64

In [12]:
trains['speed'][0]=50

C:\Users\HARSHIT\AppData\Local\Temp\ipykernel_6240\317593277.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trains['speed'][0]=50

In [13]:
trains

   train no.  speed  no. of stations     city
0      45125     50               15    patna
1      79882     87               28   jhansi
2      89645    364               12    bhind
3      54621     55                8  gwalior

In [14]:
trains.index = ['first', 'second', 'third', 'fourth']

In [15]:
trains

        train no.  speed  no. of stations     city
first       45125     50               15    patna
second      79882     87               28   jhansi
third       89645    364               12    bhind
fourth      54621     55                8  gwalior

In [16]:
ser = pd.Series(np.random.rand(23))

In [17]:
ser

0     0.190060
1     0.068736
2     0.631353
3     0.223359
4     0.872586
5     0.758666
6     0.417753
7     0.729185
8     0.700882
9     0.110763
10    0.187813
11    0.124834
12    0.593791
13    0.560226
14    0.136046
15    0.775634
16    0.929424
17    0.901064
18    0.222714
19    0.804300
20    0.520518
21    0.424682
22    0.302945
dtype: float64

In [18]:
type(ser)

pandas.core.series.Series

In [19]:
newdf = pd.DataFrame(np.random.rand(334,5), index=np.arange(334))

In [20]:
newdf

            0         1         2         3         4
0    0.911094  0.626737  0.197005  0.264266  0.882247
1    0.289635  0.355490  0.207340  0.538429  0.332459
2    0.967907  0.453110  0.530293  0.701117  0.865389
3    0.796108  0.164428  0.026913  0.936423  0.074086
4    0.501340  0.864506  0.600893  0.627396  0.296392
..        ...       ...       ...       ...       ...
329  0.598543  0.090856  0.274513  0.942729  0.879708
330  0.679484  0.355395  0.428784  0.939135  0.259736
331  0.617502  0.339597  0.803813  0.959372  0.712993
332  0.022404  0.072172  0.614140  0.116065  0.316000
333  0.084301  0.046891  0.934515  0.216065  0.485512

[334 rows x 5 columns]

In [21]:
newdf.head()

          0         1         2         3         4
0  0.911094  0.626737  0.197005  0.264266  0.882247
1  0.289635  0.355490  0.207340  0.538429  0.332459
2  0.967907  0.453110  0.530293  0.701117  0.865389
3  0.796108  0.164428  0.026913  0.936423  0.074086
4  0.501340  0.864506  0.600893  0.627396  0.296392

In [22]:
type(newdf)

pandas.core.frame.DataFrame

In [23]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [24]:
 newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int32', length=334)

In [25]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [26]:
newdf.to_numpy

<bound method DataFrame.to_numpy of             0         1         2         3         4
0    0.911094  0.626737  0.197005  0.264266  0.882247
1    0.289635  0.355490  0.207340  0.538429  0.332459
2    0.967907  0.453110  0.530293  0.701117  0.865389
3    0.796108  0.164428  0.026913  0.936423  0.074086
4    0.501340  0.864506  0.600893  0.627396  0.296392
..        ...       ...       ...       ...       ...
329  0.598543  0.090856  0.274513  0.942729  0.879708
330  0.679484  0.355395  0.428784  0.939135  0.259736
331  0.617502  0.339597  0.803813  0.959372  0.712993
332  0.022404  0.072172  0.614140  0.116065  0.316000
333  0.084301  0.046891  0.934515  0.216065  0.485512

[334 rows x 5 columns]>

In [27]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.911094,0.289635,0.967907,0.796108,0.501340,0.907720,0.025459,0.526482,0.702896,0.276112,...,0.857082,0.673192,0.756702,0.583606,0.313098,0.598543,0.679484,0.617502,0.022404,0.084301
1,0.626737,0.355490,0.453110,0.164428,0.864506,0.075020,0.609575,0.141102,0.315811,0.166864,...,0.335706,0.833722,0.176177,0.234142,0.993162,0.090856,0.355395,0.339597,0.072172,0.046891
2,0.197005,0.207340,0.530293,0.026913,0.600893,0.691224,0.155309,0.327047,0.430409,0.847383,...,0.978852,0.392479,0.022018,0.379994,0.869386,0.274513,0.428784,0.803813,0.614140,0.934515
3,0.264266,0.538429,0.701117,0.936423,0.627396,0.027379,0.016189,0.911488,0.001192,0.475383,...,0.718516,0.927386,0.039195,0.280736,0.263752,0.942729,0.939135,0.959372,0.116065,0.216065
4,0.882247,0.332459,0.865389,0.074086,0.296392,0.360585,0.523707,0.808050,0.073845,0.762113,...,0.055856,0.863199,0.778922,0.147311,0.775279,0.879708,0.259736,0.712993,0.316000,0.485512

In [28]:
newdf.sort_index(axis=0,ascending=False)

            0         1         2         3         4
333  0.084301  0.046891  0.934515  0.216065  0.485512
332  0.022404  0.072172  0.614140  0.116065  0.316000
331  0.617502  0.339597  0.803813  0.959372  0.712993
330  0.679484  0.355395  0.428784  0.939135  0.259736
329  0.598543  0.090856  0.274513  0.942729  0.879708
..        ...       ...       ...       ...       ...
4    0.501340  0.864506  0.600893  0.627396  0.296392
3    0.796108  0.164428  0.026913  0.936423  0.074086
2    0.967907  0.453110  0.530293  0.701117  0.865389
1    0.289635  0.355490  0.207340  0.538429  0.332459
0    0.911094  0.626737  0.197005  0.264266  0.882247

[334 rows x 5 columns]

view pointer

In [29]:
newdf2 = newdf

copy

In [30]:
newdf3 = newdf.copy()

In [31]:
newdf.loc[0,0] = 65

In [32]:
newdf.head(2)

           0         1         2         3         4
0  65.000000  0.626737  0.197005  0.264266  0.882247
1   0.289635  0.355490  0.207340  0.538429  0.332459

In [33]:
newdf.columns = list("ABCDE")

In [34]:
 newdf.loc[0,'A'] = 456

In [35]:
newdf

              A         B         C         D         E
0    456.000000  0.626737  0.197005  0.264266  0.882247
1      0.289635  0.355490  0.207340  0.538429  0.332459
2      0.967907  0.453110  0.530293  0.701117  0.865389
3      0.796108  0.164428  0.026913  0.936423  0.074086
4      0.501340  0.864506  0.600893  0.627396  0.296392
..          ...       ...       ...       ...       ...
329    0.598543  0.090856  0.274513  0.942729  0.879708
330    0.679484  0.355395  0.428784  0.939135  0.259736
331    0.617502  0.339597  0.803813  0.959372  0.712993
332    0.022404  0.072172  0.614140  0.116065  0.316000
333    0.084301  0.046891  0.934515  0.216065  0.485512

[334 rows x 5 columns]

In [36]:
newdf = newdf.drop(0, axis=1)

KeyError: '[0] not found in axis'

In [38]:
newdf.loc[[1,2], ['C', 'D']]

          C         D
1  0.207340  0.538429
2  0.530293  0.701117

In [39]:
newdf.loc[:, ['C', 'D']]

            C         D
0    0.197005  0.264266
1    0.207340  0.538429
2    0.530293  0.701117
3    0.026913  0.936423
4    0.600893  0.627396
..        ...       ...
329  0.274513  0.942729
330  0.428784  0.939135
331  0.803813  0.959372
332  0.614140  0.116065
333  0.934515  0.216065

[334 rows x 2 columns]

In [40]:
newdf.loc[(newdf['A']<0.3) & (newdf['C']>0.1)]

            A         B         C         D         E
1    0.289635  0.355490  0.207340  0.538429  0.332459
6    0.025459  0.609575  0.155309  0.016189  0.523707
9    0.276112  0.166864  0.847383  0.475383  0.762113
10   0.173122  0.321269  0.640767  0.582969  0.058475
15   0.229617  0.785720  0.755926  0.685284  0.949888
..        ...       ...       ...       ...       ...
311  0.218055  0.401674  0.453056  0.713410  0.654398
312  0.191648  0.252806  0.240347  0.292372  0.003135
321  0.297928  0.129617  0.623022  0.964181  0.573651
332  0.022404  0.072172  0.614140  0.116065  0.316000
333  0.084301  0.046891  0.934515  0.216065  0.485512

[85 rows x 5 columns]

In [41]:
newdf.iloc[0,4]

0.882247204303434

.loc[] selects data by labels (names), while .iloc[] selects data by integer positions (numbers).

In [42]:
newdf.head(3)

            A         B         C         D         E
0  456.000000  0.626737  0.197005  0.264266  0.882247
1    0.289635  0.355490  0.207340  0.538429  0.332459
2    0.967907  0.453110  0.530293  0.701117  0.865389

In [43]:
newdf.drop(['A'], axis=1)

            B         C         D         E
0    0.626737  0.197005  0.264266  0.882247
1    0.355490  0.207340  0.538429  0.332459
2    0.453110  0.530293  0.701117  0.865389
3    0.164428  0.026913  0.936423  0.074086
4    0.864506  0.600893  0.627396  0.296392
..        ...       ...       ...       ...
329  0.090856  0.274513  0.942729  0.879708
330  0.355395  0.428784  0.939135  0.259736
331  0.339597  0.803813  0.959372  0.712993
332  0.072172  0.614140  0.116065  0.316000
333  0.046891  0.934515  0.216065  0.485512

[334 rows x 4 columns]

In [44]:
newdf.drop([0])

            A         B         C         D         E
1    0.289635  0.355490  0.207340  0.538429  0.332459
2    0.967907  0.453110  0.530293  0.701117  0.865389
3    0.796108  0.164428  0.026913  0.936423  0.074086
4    0.501340  0.864506  0.600893  0.627396  0.296392
5    0.907720  0.075020  0.691224  0.027379  0.360585
..        ...       ...       ...       ...       ...
329  0.598543  0.090856  0.274513  0.942729  0.879708
330  0.679484  0.355395  0.428784  0.939135  0.259736
331  0.617502  0.339597  0.803813  0.959372  0.712993
332  0.022404  0.072172  0.614140  0.116065  0.316000
333  0.084301  0.046891  0.934515  0.216065  0.485512

[333 rows x 5 columns]

In [45]:
newdf.head()

            A         B         C         D         E
0  456.000000  0.626737  0.197005  0.264266  0.882247
1    0.289635  0.355490  0.207340  0.538429  0.332459
2    0.967907  0.453110  0.530293  0.701117  0.865389
3    0.796108  0.164428  0.026913  0.936423  0.074086
4    0.501340  0.864506  0.600893  0.627396  0.296392

In [46]:
newdf.reset_index(drop=True, inplace=True)

In [47]:
newdf.loc[:,['B']]= None

In [48]:
newdf

              A     B         C         D         E
0    456.000000  None  0.197005  0.264266  0.882247
1      0.289635  None  0.207340  0.538429  0.332459
2      0.967907  None  0.530293  0.701117  0.865389
3      0.796108  None  0.026913  0.936423  0.074086
4      0.501340  None  0.600893  0.627396  0.296392
..          ...   ...       ...       ...       ...
329    0.598543  None  0.274513  0.942729  0.879708
330    0.679484  None  0.428784  0.939135  0.259736
331    0.617502  None  0.803813  0.959372  0.712993
332    0.022404  None  0.614140  0.116065  0.316000
333    0.084301  None  0.934515  0.216065  0.485512

[334 rows x 5 columns]

In [49]:
df = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'],
                   "toy" : [np.nan, 'Batmobile', 'Bullwhip'],
                   "born": [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT]})

In [50]:
df.head()

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [51]:
df.dropna(how='all')

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   toy     2 non-null      object
 2   born    1 non-null      datetime64[ns]
dtypes: datetime64[ns](1), object(2)
memory usage: 204.0+ bytes

In [53]:
import pandas as pd
print(pd.__version__)

2.1.4

In [54]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)

x    1
y    7
z    2
dtype: int64

In [55]:
import pandas as pd

calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories)

print(myvar)

day1    420
day2    380
day3    390
dtype: int64

In [56]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

myvar = pd.DataFrame(data)

In [57]:
myvar

   calories  duration
0       420        50
1       380        40
2       390        45

In [ ]:
# print(newdf.to_string())

use to_string() to print the entire DataFrame.

In [5]:
import pandas as pd

data = {
  "Duration":{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60
  },
  "Pulse":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102
  },
  "Maxpulse":{
    "0":130,
    "1":145,
    "2":135,
    "3":175,
    "4":148,
    "5":127
  },
  "Calories":{
    "0":409,
    "1":479,
    "2":340,
    "3":282,
    "4":406,
    "5":300
  }
}

df = pd.DataFrame(data)

print(df)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300

In [11]:
new_df = df.dropna()

#to change the og dataframe, use dropna(inplace = True)

fillna() method allows us to replace empty cells with a value

In [12]:
print(df)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300

In [14]:
new_df.fillna(50, inplace = True)

In [15]:
print(new_df)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300

In [22]:
import pandas as pd
import numpy as np # Import numpy for NaN values

# Define the data structure
data = {
    'Duration': [60, 60, 60, 45, 45, 60, 60, 450, 30, 60, 60, 60, 60, 60, 60, 60, 60, 60, 45, 60, 45, 60, 45, 60, 45, 60, 60, 60, 60, 60, 60, 60],
    'Date': ['2020/12/01', '2020/12/02', '2020/12/03', '2020/12/04', '2020/12/05', '2020/12/06', '2020/12/07', '2020/12/08', '2020/12/09', '2020/12/10', '2020/12/11', '2020/12/12', '2020/12/12', '2020/12/13', '2020/12/14', '2020/12/15', '2020/12/16', '2020/12/17', '2020/12/18', '2020/12/19', '2020/12/20', '2020/12/21', np.nan, '2020/12/23', '2020/12/24', '2020/12/25', 20201226, '2020/12/27', '2020/12/28', '2020/12/29', '2020/12/30', '2020/12/31'],
    'Pulse': [110, 117, 103, 109, 117, 102, 110, 104, 109, 98, 103, 100, 100, 106, 104, 98, 98, 100, 90, 103, 97, 108, 100, 130, 105, 102, 100, 92, 103, 100, 102, 92],
    'Maxpulse': [130, 145, 135, 175, 148, 127, 136, 134, 133, 124, 147, 120, 120, 128, 132, 123, 120, 120, 112, 123, 125, 131, 119, 101, 132, 126, 120, 118, 132, 132, 129, 115],
    'Calories': [409.1, 479.0, 340.0, 282.4, 406.0, 300.0, 374.0, 253.3, 195.1, 269.0, 329.3, 250.7, 250.7, 345.3, 379.3, 275.0, 215.2, 300.0, np.nan, 323.0, 243.0, 364.2, 282.0, 300.0, 246.0, 334.5, 250.0, 241.0, np.nan, 280.0, 380.3, 243.0]
}

# Create the DataFrame
df = pd.DataFrame(data)

# Print the resulting DataFrame to display it
print(df)

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7        450  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
18        45  2020/12/18     90       112       NaN
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
22        45         NaN    100       119     282.0
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60    20201226    100       120     250.0
27        60  2020/12/27     92       118     241.0
28        60  2020/12/28    103       132       NaN
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0

#df['Date'] = pd.to_datetime(df['Date'], format='mixed')

print(df.to_string())

In [23]:
print(df)

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7        450  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
18        45  2020/12/18     90       112       NaN
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
22        45         NaN    100       119     282.0
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60    20201226    100       120     250.0
27        60  2020/12/27     92       118     241.0
28        60  2020/12/28    103       132       NaN
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0

In [26]:
df.loc[7, 'Duration'] = 45
print(df.to_string())

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7         45  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
18        45  2020/12/18     90       112       NaN
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
22        45         NaN    100       119     282.0
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60    20201226    100       120     250.0
27        60  2020/12/27     92       118     241.0
28        60  2020/12/28    103       132       NaN
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0

In [31]:
df.loc[7, 'Duration'] = 500
print(df.to_string())

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7        500  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
18        45  2020/12/18     90       112       NaN
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
22        45         NaN    100       119     282.0
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60    20201226    100       120     250.0
27        60  2020/12/27     92       118     241.0
28        60  2020/12/28    103       132       NaN
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0

In [32]:
for x in df.index:
  if df.loc[x, "Duration"] > 120:
    df.loc[x, "Duration"] = 120

print(df.to_string())

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7        120  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
18        45  2020/12/18     90       112       NaN
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
22        45         NaN    100       119     282.0
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60    20201226    100       120     250.0
27        60  2020/12/27     92       118     241.0
28        60  2020/12/28    103       132       NaN
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0

In [34]:
for x in df.index:
  if df.loc[x, "Duration"] > 120:
    df.drop(x, inplace = True)
print(df.to_string())

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7        120  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
18        45  2020/12/18     90       112       NaN
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
22        45         NaN    100       119     282.0
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60    20201226    100       120     250.0
27        60  2020/12/27     92       118     241.0
28        60  2020/12/28    103       132       NaN
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0

In [35]:
print(df.duplicated())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
dtype: bool

In [37]:
df.drop_duplicates(inplace = True)
print(df.to_string())

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7        120  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
18        45  2020/12/18     90       112       NaN
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
22        45         NaN    100       119     282.0
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60    20201226    100       120     250.0
27        60  2020/12/27     92       118     241.0
28        60  2020/12/28    103       132       NaN
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0

## corr()

In [42]:
numeric_df = df.drop('Date', axis=1)

# Calculate and print the correlation matrix on only the numeric columns
print(numeric_df.corr())

          Duration     Pulse  Maxpulse  Calories
Duration  1.000000 -0.025286 -0.071409  0.047694
Pulse    -0.025286  1.000000  0.269672  0.506593
Maxpulse -0.071409  0.269672  1.000000  0.344494
Calories  0.047694  0.506593  0.344494  1.000000

In [44]:
import pandas as pd
import matplotlib.pylot as plt
df.plot()
plt.show()

ModuleNotFoundError: No module named 'matplotlib.pylot'

### kind = 'scatter'

In [ ]:
df.plot(kind = 'scatter', x = 'Duration', y = 'Calories')

plt.show()

### kind = 'hist'

In [ ]:
df["Duration"].plot(kind = 'hist')